28/07/21 (01:12:50) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 919, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
10/09/21 (13:31:28) | ERROR: Data collection thread failed with exception: Sign not allowed in string format specifier
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2939, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3971, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2719, in _draw_fg
    label = (f'{THEME.title}{Fx.b}{Mv.to(y, x)}{"Pid:":>7} {"Program:" if prog_len > 8 else "Prg:":<{prog_len}}' + (f'{"Arguments:":<{arg_len-4}}' if arg_len else "") +
ValueError: Sign not allowed in string format specifier
10/09/21 (13:31:28) | WARNING: Exiting with errorcode (1). Runtime 0:00:00 

11/09/21 (14:00:02) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (14:01:31) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (14:01:59) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (14:02:12) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (14:02:18) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
11/09/21 (15:19:51) | ERROR: Data collection thread failed with exception: 'pid'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 2939, in _runner
    collector._draw()
  File "/usr/bin/bpytop", line 3971, in _draw
    ProcBox._draw_fg()
  File "/usr/bin/bpytop", line 2618, in _draw_fg
    f'{Mv.to(dy-1, x+1)}{THEME.proc_box(Symbol.title_left)}{Fx.b}{THEME.title(str(proc.details["pid"]))}{Fx.ub}{THEME.proc_box(Symbol.title_right)}'
KeyError: 'pid'
11/09/21 (15:19:53) | WARNING: Exiting with errorcode (1). Runtime 1:02:06 

19/09/21 (18:56:38) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 937, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
22/09/21 (06:22:04) | ERROR: Input thread failed with exception: [Errno 5] Input/output error
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 937, in _get_key
    input_key += sys.stdin.read(1)						#* Read 1 key safely with blocking on
OSError: [Errno 5] Input/output error
29/09/21 (07:02:52) | ERROR: Remote end closed connection without response
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 5009, in _checker
    with urllib.request.urlopen("https://github.com/aristocratos/bpytop/raw/master/bpytop.py", timeout=5) as source: # type: ignore
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 288, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
30/09/21 (06:03:25) | WARNING: Config key "cpu_sensor" does not contain an available sensor!
30/09/21 (06:03:25) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (06:21:21) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (06:35:19) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (06:40:18) | ERROR: Exception when sending signal 9 to pid 5727
30/09/21 (06:40:18) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 5459, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
30/09/21 (06:40:25) | ERROR: Exception when sending signal 9 to pid 5727
30/09/21 (06:40:25) | ERROR: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 5459, in process_keys
    os.kill(pid, sig)
PermissionError: [Errno 1] Operation not permitted
30/09/21 (06:47:40) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (06:52:34) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (07:27:55) | ERROR: [Errno 2] No such file or directory: '/root/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/bpytop/themes'
30/09/21 (07:32:50) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (07:41:25) | ERROR: [Errno 2] No such file or directory: '/root/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/root/.config/bpytop/themes'
30/09/21 (08:07:56) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:13:31) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:14:02) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:14:06) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:14:11) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:14:18) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:14:29) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:14:35) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:14:38) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:15:22) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:47:05) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (08:48:12) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (12:08:38) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
30/09/21 (12:09:56) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
01/10/21 (00:14:08) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
01/10/21 (00:18:49) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
01/10/21 (00:21:12) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
01/10/21 (05:57:27) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
01/10/21 (06:29:13) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
01/10/21 (06:34:03) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
01/10/21 (08:22:03) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
01/10/21 (09:16:38) | ERROR: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/local/bin/bpytop", line 1337, in refresh
    for f in os.listdir(d):
FileNotFoundError: [Errno 2] No such file or directory: '/home/lespink/.config/bpytop/themes'
